"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Check,
  Download,
  Eye,
  FileArchive,
  FileCode2,
  Link2,
  Lock,
  Unlock,
  RotateCcw,
  Sparkles,
  ExternalLink,
  ShieldCheck,
} from "lucide-react";
import { EASE } from "@/components/landing/reveal";

export function InteractiveHeroDemo() {
  const [pin, setPin] = useState<string>("");
  const [isUnlocked, setIsUnlocked] = useState<boolean>(false);
  const [isPaid, setIsPaid] = useState<boolean>(false);
  const [activeTab, setActiveTab] = useState<number>(0);
  const [events, setEvents] = useState<Array<{ text: string; time: string }>>([
    { text: "Portal generated by freelancer", time: "10m ago" },
  ]);

  const handlePinInput = (digit: string) => {
    if (pin.length < 4) {
      const nextPin = pin + digit;
      setPin(nextPin);
      if (nextPin === "1234") {
        setTimeout(() => {
          setIsUnlocked(true);
          setEvents((prev) => [
            { text: "Client entered PIN 1234", time: "Just now" },
            { text: "Previewed brand-system.fig", time: "Just now" },
            ...prev,
          ]);
        }, 300);
      }
    }
  };

  const autoUnlock = () => {
    setPin("1234");
    setTimeout(() => {
      setIsUnlocked(true);
      setEvents((prev) => [
        { text: "Client entered PIN 1234", time: "Just now" },
        { text: "Previewed brand-system.fig", time: "Just now" },
        ...prev,
      ]);
    }, 200);
  };

  const handleTogglePayment = () => {
    const nextPaid = !isPaid;
    setIsPaid(nextPaid);
    if (nextPaid) {
      setEvents((prev) => [
        { text: "Payment settled ($2,400) — Downloads unlocked", time: "Just now" },
        ...prev,
      ]);
    } else {
      setEvents((prev) => [
        { text: "Payment marked pending — Downloads locked", time: "Just now" },
        ...prev,
      ]);
    }
  };

  const resetSandbox = () => {
    setPin("");
    setIsUnlocked(false);
    setIsPaid(false);
    setActiveTab(0);
    setEvents([{ text: "Portal generated by freelancer", time: "10m ago" }]);
  };

  const deliverables = [
    {
      id: 0,
      icon: Link2,
      name: "brand-system.fig",
      meta: "Figma embed · 14 artboards",
      type: "Figma",
    },
    {
      id: 1,
      icon: FileCode2,
      name: "navbar.tsx",
      meta: "Code · TypeScript React",
      type: "Code",
    },
    {
      id: 2,
      icon: FileArchive,
      name: "final-assets.zip",
      meta: "Deliverables · 42.8 MB",
      type: "ZIP",
    },
  ];

  return (
    <figure className="border-t border-zinc-200">
      <div className="mx-auto max-w-6xl px-6 pt-12">
        {/* Interactive Sandbox Header Callout */}
        <div className="mb-4 flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2">
            <span className="flex size-2 bg-emerald-500" aria-hidden />
            <p className="font-mono text-[11px] uppercase tracking-[0.2em] text-[#151B45]">
              Interactive Sandbox Demo
            </p>
            <span className="font-mono text-xs text-zinc-400">
              [Test the client experience live]
            </span>
          </div>

          <div className="flex items-center gap-2">
            {!isUnlocked ? (
              <button
                type="button"
                onClick={autoUnlock}
                className="inline-flex items-center gap-1.5 border border-zinc-300 bg-white px-3 py-1 font-mono text-xs text-[#151B45] transition-colors hover:border-[#151B45] hover:bg-zinc-50"
              >
                <span>Auto-fill PIN: 1234 →</span>
              </button>
            ) : (
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={handleTogglePayment}
                  className={`inline-flex items-center gap-1.5 border px-3 py-1 font-mono text-xs transition-colors ${
                    isPaid
                      ? "border-emerald-300 bg-emerald-50 text-emerald-800 hover:bg-emerald-100"
                      : "border-[#151B45] bg-[#151B45] text-[#F8F7FC] hover:bg-zinc-800"
                  }`}
                >
                  {isPaid ? (
                    <>
                      <Check className="size-3 text-emerald-600" strokeWidth={2.5} />
                      <span>Simulate Unpaid (Relock)</span>
                    </>
                  ) : (
                    <>
                      <Unlock className="size-3" strokeWidth={2} />
                      <span>Simulate Payment ($2,400 Paid)</span>
                    </>
                  )}
                </button>
                <button
                  type="button"
                  onClick={resetSandbox}
                  className="inline-flex items-center gap-1 border border-zinc-200 bg-white px-2.5 py-1 font-mono text-xs text-zinc-500 hover:bg-zinc-50 hover:text-zinc-800"
                  title="Reset Sandbox"
                >
                  <RotateCcw className="size-3" />
                  <span>Reset</span>
                </button>
              </div>
            )}
          </div>
        </div>

        {/* Outer Browser Frame */}
        <div className="border border-zinc-200 bg-white shadow-xs">
          {/* Chrome bar */}
          <div className="flex items-center gap-2 border-b border-zinc-200 px-5 py-3">
            <span className="flex gap-1.5" aria-hidden>
              <span className="size-2.5 bg-zinc-300" />
              <span className="size-2.5 bg-zinc-300" />
              <span className="size-2.5 bg-zinc-300" />
            </span>
            <span className="ml-3 truncate font-mono text-[11px] text-zinc-400">
              portalize.site/p/acme-brand-2026
            </span>
            <span className="ml-auto flex items-center gap-1.5 font-mono text-[11px] text-zinc-400">
              <Lock className="size-3" strokeWidth={2} />
              {isUnlocked ? "PIN Verified (1234)" : "Protected with 4-digit PIN"}
            </span>
          </div>

          <AnimatePresence mode="wait">
            {!isUnlocked ? (
              /* State 1: Interactive PIN Entry Mock */
              <motion.div
                key="pin-screen"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.3, ease: EASE }}
                className="flex flex-col items-center justify-center px-6 py-20 text-center sm:py-28"
              >
                <div className="mx-auto max-w-sm">
                  <span className="flex size-12 items-center justify-center border border-zinc-200 bg-zinc-50 text-[#151B45] mx-auto">
                    <Lock className="size-5" strokeWidth={1.75} />
                  </span>

                  <p className="mt-4 font-mono text-[11px] uppercase tracking-[0.2em] text-zinc-400">
                    Acme Studio · Client Delivery
                  </p>
                  <h3 className="mt-1 text-xl font-medium tracking-tight text-[#151B45]">
                    Enter 4-digit PIN to access portal
                  </h3>
                  <p className="mt-2 text-xs text-zinc-500">
                    No login required. Click the keypad or press &ldquo;Auto-fill PIN: 1234&rdquo; above.
                  </p>

                  {/* 4 PIN display boxes */}
                  <div className="mt-6 flex justify-center gap-3">
                    {[0, 1, 2, 3].map((idx) => (
                      <div
                        key={idx}
                        className={`flex size-12 items-center justify-center border font-mono text-xl font-medium transition-all ${
                          pin.length > idx
                            ? "border-[#151B45] bg-[#151B45] text-white"
                            : "border-zinc-200 bg-white text-zinc-400"
                        }`}
                      >
                        {pin.length > idx ? "•" : ""}
                      </div>
                    ))}
                  </div>

                  {/* On-screen Keypad */}
                  <div className="mt-6 grid grid-cols-3 gap-2 max-w-[240px] mx-auto">
                    {["1", "2", "3", "4", "5", "6", "7", "8", "9", "C", "0", "→"].map((btn) => (
                      <button
                        key={btn}
                        type="button"
                        onClick={() => {
                          if (btn === "C") setPin("");
                          else if (btn === "→") {
                            if (pin === "1234") autoUnlock();
                          } else handlePinInput(btn);
                        }}
                        className="flex h-10 items-center justify-center border border-zinc-200 bg-zinc-50 font-mono text-sm font-medium text-[#151B45] transition-colors hover:bg-zinc-100 active:bg-zinc-200"
                      >
                        {btn}
                      </button>
                    ))}
                  </div>

                  <p className="mt-5 font-mono text-[11px] text-zinc-400">
                    Demo PIN: <strong className="text-[#151B45]">1234</strong>
                  </p>
                </div>
              </motion.div>
            ) : (
              /* State 2: Unlocked Interactive Portal */
              <motion.div
                key="unlocked-portal"
                initial={{ opacity: 0, scale: 0.98 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.4, ease: EASE }}
                className="grid lg:grid-cols-[1fr_300px]"
              >
                {/* Main Content Column */}
                <div className="min-w-0">
                  {/* Project Header */}
                  <div className="flex items-start justify-between gap-4 px-5 py-6 sm:px-7">
                    <div>
                      <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-zinc-400">
                        Acme Co. · Deliverable Portal
                      </p>
                      <h3 className="mt-1.5 text-xl font-medium tracking-tight text-[#151B45]">
                        Brand Identity &amp; Website Design
                      </h3>
                    </div>
                    <span className="shrink-0 border border-zinc-200 px-2.5 py-1 font-mono text-[11px] text-zinc-500">
                      In review
                    </span>
                  </div>

                  {/* Dynamic Payment Banner */}
                  <div className="mx-5 mb-4 sm:mx-7">
                    <AnimatePresence mode="wait">
                      {!isPaid ? (
                        <motion.div
                          key="unpaid-banner"
                          initial={{ opacity: 0, y: -6 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -6 }}
                          className="flex flex-col gap-3 border border-amber-200 bg-amber-50/60 p-4 sm:flex-row sm:items-center sm:justify-between"
                        >
                          <div className="space-y-0.5">
                            <p className="flex items-center gap-2 font-mono text-[11px] font-medium uppercase tracking-[0.16em] text-amber-900">
                              <Lock className="size-3.5 shrink-0" strokeWidth={2} />
                              Payment Pending · Deliverables Locked
                            </p>
                            <p className="text-xs text-amber-800">
                              Previews are watermarked. High-resolution downloads unlock when invoice clears.
                            </p>
                          </div>
                          <button
                            type="button"
                            onClick={handleTogglePayment}
                            className="inline-flex shrink-0 items-center justify-center gap-1.5 border border-[#151B45] bg-[#151B45] px-3.5 py-2 font-mono text-xs text-[#F8F7FC] hover:bg-zinc-800"
                          >
                            <span>Pay Invoice ($2,400) ↗</span>
                          </button>
                        </motion.div>
                      ) : (
                        <motion.div
                          key="paid-banner"
                          initial={{ opacity: 0, y: -6 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: -6 }}
                          className="flex flex-col gap-2 border border-emerald-200 bg-emerald-50/60 p-4 sm:flex-row sm:items-center sm:justify-between"
                        >
                          <p className="flex items-center gap-2 font-mono text-[11px] font-medium uppercase tracking-[0.16em] text-emerald-900">
                            <Check className="size-3.5 text-emerald-600" strokeWidth={2.5} />
                            Invoice Paid ($2,400) · All Deliverables Unlocked
                          </p>
                          <span className="font-mono text-xs text-emerald-700">
                            ✓ Watermarks Removed
                          </span>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>

                  {/* Tabbed Deliverables List */}
                  <div className="border-t border-zinc-200">
                    <div className="grid grid-cols-3 border-b border-zinc-200 bg-zinc-50 font-mono text-xs text-zinc-500">
                      {deliverables.map((d, i) => (
                        <button
                          key={d.id}
                          type="button"
                          onClick={() => {
                            setActiveTab(i);
                            setEvents((prev) => [
                              { text: `Previewed ${d.name}`, time: "Just now" },
                              ...prev,
                            ]);
                          }}
                          className={`flex items-center justify-center gap-2 py-3 transition-colors ${
                            activeTab === i
                              ? "border-b-2 border-[#151B45] bg-white font-medium text-[#151B45]"
                              : "hover:bg-zinc-100"
                          }`}
                        >
                          <d.icon className="size-3.5" />
                          <span className="truncate">{d.name}</span>
                        </button>
                      ))}
                    </div>

                    {/* Active Deliverable Preview Canvas */}
                    <div className="p-5 sm:p-7">
                      {activeTab === 0 && (
                        /* Figma Preview Mock */
                        <div className="relative border border-zinc-200 bg-zinc-950 p-6 text-center text-white">
                          {!isPaid && (
                            <div className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden">
                              <span className="rotate-[-18deg] font-mono text-3xl font-bold uppercase tracking-[0.3em] text-white/15 sm:text-4xl">
                                PORTALIZE PREVIEW · UNPAID
                              </span>
                            </div>
                          )}
                          <div className="space-y-3">
                            <span className="inline-flex size-10 items-center justify-center border border-zinc-700 bg-zinc-900 text-white">
                              <Link2 className="size-5" />
                            </span>
                            <p className="text-sm font-medium">Figma Interactive Design Canvas</p>
                            <p className="font-mono text-xs text-zinc-400">
                              Frame: Desktop Homepage v3.4 (14 artboards)
                            </p>
                          </div>
                        </div>
                      )}

                      {activeTab === 1 && (
                        /* Code Preview Mock */
                        <div className="relative overflow-hidden border border-zinc-200 bg-zinc-900 p-5 font-mono text-xs text-zinc-300">
                          {!isPaid && (
                            <div className="pointer-events-none absolute inset-0 flex items-center justify-center overflow-hidden">
                              <span className="rotate-[-18deg] text-2xl font-bold uppercase tracking-[0.3em] text-white/10">
                                PREVIEW ONLY
                              </span>
                            </div>
                          )}
                          <pre className="text-left leading-relaxed">
                            <span className="text-zinc-500">// src/components/navbar.tsx</span>{"\n"}
                            <span className="text-purple-400">export function</span>{" "}
                            <span className="text-blue-400">Navbar</span>() {"{\n"}
                            {"  "}<span className="text-purple-400">return</span> ({"\n"}
                            {"    "}&lt;<span className="text-emerald-400">header</span> className=&quot;<span className="text-amber-300">border-b</span>&quot;&gt;...&lt;/<span className="text-emerald-400">header</span>&gt;{"\n"}
                            {"  "});{"\n"}
                            {"}"}
                          </pre>
                        </div>
                      )}

                      {activeTab === 2 && (
                        /* ZIP Archive Download Mock */
                        <div className="border border-zinc-200 bg-zinc-50 p-6 text-center">
                          <FileArchive className="size-8 mx-auto text-[#151B45]" />
                          <p className="mt-2 text-sm font-medium text-[#151B45]">
                            final-assets-v1.0.zip (42.8 MB)
                          </p>
                          <p className="mt-1 font-mono text-xs text-zinc-500">
                            Includes SVGs, PNGs, brand guide PDF, typography files.
                          </p>
                        </div>
                      )}

                      {/* Download Action Footer */}
                      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-t border-zinc-100 pt-5">
                        <span className="font-mono text-xs text-zinc-400">
                          Status: {isPaid ? "Payment cleared · ready" : "Locked until payment"}
                        </span>

                        <button
                          type="button"
                          onClick={() => {
                            if (!isPaid) handleTogglePayment();
                          }}
                          className={`inline-flex items-center justify-center gap-2 px-5 py-2 font-mono text-xs font-medium transition-colors ${
                            isPaid
                              ? "bg-emerald-600 text-white hover:bg-emerald-700"
                              : "border border-zinc-300 bg-zinc-100 text-zinc-600 hover:border-[#151B45] hover:text-[#151B45]"
                          }`}
                        >
                          {isPaid ? (
                            <>
                              <Download className="size-3.5" />
                              <span>Download Unlocked Deliverable</span>
                            </>
                          ) : (
                            <>
                              <Lock className="size-3.5" strokeWidth={2} />
                              <span>Download Locked (Click to Unlock)</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Sidebar: Realtime Activity Feed Mock */}
                <aside className="border-t border-zinc-200 lg:border-l lg:border-t-0 bg-zinc-50/30">
                  <div className="space-y-6 p-5 sm:p-6">
                    <div>
                      <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-zinc-400">
                        Client Access
                      </p>
                      <p className="mt-1 text-2xl font-medium tracking-tight text-[#151B45]">
                        1234
                      </p>
                      <p className="mt-1 text-xs text-zinc-500">
                        4-digit PIN access. Zero client signup required.
                      </p>
                    </div>

                    <div className="border-t border-zinc-200 pt-5">
                      <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-zinc-400">
                        Payment Status
                      </p>
                      <div className="mt-2 flex items-center justify-between">
                        <span
                          className={`inline-flex items-center gap-1.5 font-mono text-xs ${
                            isPaid ? "text-emerald-700" : "text-amber-700"
                          }`}
                        >
                          <span
                            className={`size-1.5 ${isPaid ? "bg-emerald-500" : "bg-amber-500"}`}
                            aria-hidden
                          />
                          {isPaid ? "Paid ($2,400)" : "Pending ($2,400)"}
                        </span>
                        <span className="font-mono text-xs text-zinc-400">[Stripe]</span>
                      </div>
                    </div>

                    <div className="border-t border-zinc-200 pt-5">
                      <div className="flex items-center justify-between">
                        <p className="font-mono text-[11px] uppercase tracking-[0.16em] text-zinc-400">
                          Realtime Receipts
                        </p>
                        <span className="flex size-1.5 bg-emerald-500 animate-pulse" />
                      </div>
                      <ul className="mt-3 space-y-2 font-mono text-xs text-zinc-600">
                        {events.slice(0, 4).map((evt, idx) => (
                          <li key={idx} className="flex items-start justify-between gap-2">
                            <span className="truncate text-zinc-700">· {evt.text}</span>
                            <span className="shrink-0 text-[10px] text-zinc-400">{evt.time}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </aside>
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        <figcaption className="pt-4 pb-2 font-mono text-xs text-zinc-400 text-center sm:text-left">
          Fig. 01 — Live interactive sandbox: Test PIN unlock, watermarked previews, and payment escrow simulation.
        </figcaption>
      </div>
    </figure>
  );
}
